### ISSUE TITLE
specify which js file contain this variable 

### ISSUE THREAD

**Issue by smackerdodi** [micha3lb3n/SourceWolf#6]
could you make the variable file looks like this 
file https://www.example.com/admin.js contain variables 
file
end
go
======================================
file https://www.example.com/user.js contains variable 
qwe
der
frt
.....etc

**Comment by ksharinarayanan** [comment]
Thanks for suggesting this! Though the file names can be useful in some conditions, the main purpose of the variables is to create a wordlist which is non-generic and specific just to the target. Given this objective, I think it would be better if all the javascript variables are under a single file, with just the variables.

Having said that, adding this feature isn't going to be a big task. This feature will be added but I'll make this optional ( file names would be visible in verbose mode )

**Comment by ksharinarayanan** [comment]
Added this feature in [v1.5](https://github.com/micha3lb3n/SourceWolf/releases/tag/v1.5) 😀

Use the flag -v to print out the file names.

**Comment by smackerdodi** [comment]
thanks for the update . nice work
