### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sabeesh03** [micha3lb3n/SourceWolf#7]
python3 sourcewolf.py -h
Traceback (most recent call last):
  File "/root/SourceWolf/sourcewolf.py", line 9, in <module>
    from helpers.crawlResponses import crawlOutput
  File "/root/SourceWolf/helpers/crawlResponses.py", line 18, in <module>
    from helpers.getVariables import variableSearch
  File "/root/SourceWolf/helpers/getVariables.py", line 1, in <module>
    import jsbeautifier
ModuleNotFoundError: No module named 'jsbeautifier'
┌──(root💀indira)-[~/SourceWolf]
└─# pip3 install jsbeautifier
bash: pip3: command not found

**Comment by sabeesh03** [comment]
pip install jsbeautifier
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in
 January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for t
his functionality.
Requirement already satisfied: jsbeautifier in /usr/local/lib/python2.7/dist-packages (1.13.4)
Requirement already satisfied: six>=1.13.0 in /usr/local/lib/python2.7/dist-packages (from jsbeautifier) (1.15.0)
Requirement already satisfied: editorconfig>=0.12.2 in /usr/local/lib/python2.7/dist-packages (from jsbeautifier) (0.12.3)

js beautifier is already installed

**Comment by ksharinarayanan** [comment]
Python 3 required. You are using python 2!
