### ISSUE TITLE
module 'yaml' has no attribute 'full_load'

### ISSUE THREAD

**Issue by sabeesh03** [micha3lb3n/SourceWolf#9]
python3 sourcewolf.py -l domains -o output -c crawl_output
Traceback (most recent call last):
  File "sourcewolf.py", line 216, in <module>
    banner()
  File "sourcewolf.py", line 147, in banner
    local_version, latest_version, new_features, bug_fixes, info = checkUpdates()
  File "/root/SourceWolf/helpers/checkForUpdates.py", line 38, in checkUpdates
    version_info = yaml.full_load(file)
AttributeError: module 'yaml' has no attribute 'full_load'

how do i resolve it

**Comment by ksharinarayanan** [comment]
I have no issues with running the program! I think you are probably using an older version of yaml.

Can you get back to me with the output of the following commands?

```
python3
import yaml
yaml.__version__
```

Reference: [https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader](https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader)

**Comment by ksharinarayanan** [comment]
Closing the issue because of no response!
